/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio06;

import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class vista extends javax.swing.JDialog {

    /**
     * Creates new form vista
     */
    public vista(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    Ventilador obj1 = new Ventilador();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonENCENDER = new javax.swing.JButton();
        jLabelVELOCIDADMAXIMA = new javax.swing.JLabel();
        jPanelNUMVELMAX = new javax.swing.JPanel();
        jLabelVELOCIDADMAXIMANUM = new javax.swing.JLabel();
        jButtonSUBIR = new javax.swing.JButton();
        jButtonBAJAR = new javax.swing.JButton();
        jLabelVELOCIDADACTUAL = new javax.swing.JLabel();
        jPanelVELOCIDADACTUAL = new javax.swing.JPanel();
        jLabelVELOCIDADACTUALNUM = new javax.swing.JLabel();
        jLabelOSCILADOR = new javax.swing.JLabel();
        jButtonAPAGAR = new javax.swing.JButton();
        ACTDESACT = new javax.swing.JComboBox<>();
        ENCHUFARDESENCHUFAR = new javax.swing.JComboBox<>();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonENCENDER.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonENCENDER.setForeground(new java.awt.Color(0, 0, 153));
        jButtonENCENDER.setText("ENCENDER");
        jButtonENCENDER.setEnabled(false);
        jButtonENCENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENCENDERActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENCENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelVELOCIDADMAXIMA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelVELOCIDADMAXIMA.setForeground(new java.awt.Color(0, 0, 153));
        jLabelVELOCIDADMAXIMA.setText("VELOCIDAD MAXIMA");
        getContentPane().add(jLabelVELOCIDADMAXIMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabelVELOCIDADMAXIMANUM.setText("-");
        jLabelVELOCIDADMAXIMANUM.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelVELOCIDADMAXIMANUMAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanelNUMVELMAXLayout = new javax.swing.GroupLayout(jPanelNUMVELMAX);
        jPanelNUMVELMAX.setLayout(jPanelNUMVELMAXLayout);
        jPanelNUMVELMAXLayout.setHorizontalGroup(
            jPanelNUMVELMAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNUMVELMAXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVELOCIDADMAXIMANUM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNUMVELMAXLayout.setVerticalGroup(
            jPanelNUMVELMAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNUMVELMAXLayout.createSequentialGroup()
                .addComponent(jLabelVELOCIDADMAXIMANUM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNUMVELMAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 80, 30));

        jButtonSUBIR.setForeground(new java.awt.Color(0, 0, 102));
        jButtonSUBIR.setText("SUBIR");
        jButtonSUBIR.setEnabled(false);
        jButtonSUBIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSUBIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSUBIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jButtonBAJAR.setForeground(new java.awt.Color(0, 0, 102));
        jButtonBAJAR.setText("BAJAR");
        jButtonBAJAR.setEnabled(false);
        jButtonBAJAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBAJARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBAJAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabelVELOCIDADACTUAL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelVELOCIDADACTUAL.setForeground(new java.awt.Color(0, 0, 153));
        jLabelVELOCIDADACTUAL.setText("VELOCIDAD ACTUAL");
        getContentPane().add(jLabelVELOCIDADACTUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabelVELOCIDADACTUALNUM.setText("-");
        jLabelVELOCIDADACTUALNUM.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelVELOCIDADACTUALNUMAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanelVELOCIDADACTUALLayout = new javax.swing.GroupLayout(jPanelVELOCIDADACTUAL);
        jPanelVELOCIDADACTUAL.setLayout(jPanelVELOCIDADACTUALLayout);
        jPanelVELOCIDADACTUALLayout.setHorizontalGroup(
            jPanelVELOCIDADACTUALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVELOCIDADACTUALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVELOCIDADACTUALNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVELOCIDADACTUALLayout.setVerticalGroup(
            jPanelVELOCIDADACTUALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVELOCIDADACTUALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVELOCIDADACTUALNUM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelVELOCIDADACTUAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jLabelOSCILADOR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelOSCILADOR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOSCILADOR.setText("OSCILADOR");
        getContentPane().add(jLabelOSCILADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jButtonAPAGAR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAPAGAR.setForeground(new java.awt.Color(204, 0, 0));
        jButtonAPAGAR.setText("APAGAR");
        jButtonAPAGAR.setEnabled(false);
        jButtonAPAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPAGARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAPAGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, -1, -1));

        ACTDESACT.setFont(new java.awt.Font("Agency FB", 3, 14)); // NOI18N
        ACTDESACT.setForeground(new java.awt.Color(204, 204, 0));
        ACTDESACT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVADO", "DESACTIVADO" }));
        ACTDESACT.setEnabled(false);
        ACTDESACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTDESACTActionPerformed(evt);
            }
        });
        getContentPane().add(ACTDESACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        ENCHUFARDESENCHUFAR.setFont(new java.awt.Font("Felix Titling", 2, 14)); // NOI18N
        ENCHUFARDESENCHUFAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENCHUFAR", "DESENCHUFAR" }));
        ENCHUFARDESENCHUFAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENCHUFARDESENCHUFARActionPerformed(evt);
            }
        });
        getContentPane().add(ENCHUFARDESENCHUFAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, -1));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio06/imagen/CMpQHV.jpg"))); // NOI18N
        imagen.setText("jLabel1");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    
    
    
    
    private void jLabelVELOCIDADMAXIMANUMAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelVELOCIDADMAXIMANUMAncestorAdded
        // TODO add your handling code here:
           jLabelVELOCIDADMAXIMANUM.setText(String.valueOf(obj1.getVelocidadMaxima()));

    }//GEN-LAST:event_jLabelVELOCIDADMAXIMANUMAncestorAdded

    private void jLabelVELOCIDADACTUALNUMAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelVELOCIDADACTUALNUMAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabelVELOCIDADACTUALNUMAncestorAdded

    private void jButtonENCENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENCENDERActionPerformed
        // TODO add your handling code here:
        obj1.setEncendido(true);
        jButtonAPAGAR.setEnabled(true);
        ACTDESACT.setEnabled(true);
        jButtonSUBIR.setEnabled(true);
        jButtonBAJAR.setEnabled(true);
        
    }//GEN-LAST:event_jButtonENCENDERActionPerformed

    private void jButtonSUBIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSUBIRActionPerformed
        // TODO add your handling code here:
        
       
    
        jLabelVELOCIDADACTUALNUM.setText(String.valueOf(obj1.SubirVelocidad()));
        
        if (obj1.VelocidadActual>=10) 
        {
            JOptionPane.showMessageDialog(null, "Velocidad Maxima Alcanzada");
            obj1.setVelocidadActual(10-1);
        }
        
       
        
    }//GEN-LAST:event_jButtonSUBIRActionPerformed

    private void jButtonBAJARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBAJARActionPerformed
        // TODO add your handling code here:
        
        jLabelVELOCIDADACTUALNUM.setText(String.valueOf(obj1.BajarVelocidad()));
        
        if (obj1.VelocidadActual==0) 
        {
            JOptionPane.showMessageDialog(null,"Velocidad Minima Alcanzada");
            obj1.setVelocidadActual(1);
            jLabelVELOCIDADACTUALNUM.setText(String.valueOf(obj1.VelocidadActual));
                    
        }
        
    }//GEN-LAST:event_jButtonBAJARActionPerformed

    private void jButtonAPAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPAGARActionPerformed
        // TODO add your handling code here:
    
       
            obj1.Apagar();
            JOptionPane.showMessageDialog(null, "Ventilador Apagado");
            obj1.setVelocidadActual(0);
            jLabelVELOCIDADACTUALNUM.setText(String.valueOf(obj1.getVelocidadActual()));
            ACTDESACT.setEnabled(false);
        
     
    }//GEN-LAST:event_jButtonAPAGARActionPerformed

    private void ACTDESACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTDESACTActionPerformed
        // TODO add your handling code here:
        if (ACTDESACT.getSelectedItem().equals("ACTIVADO")) 
        {
            obj1.Oscilar();
            
            if (obj1.Oscilar()==true) 
            {
                 JOptionPane.showMessageDialog(null,"OSCILADOR ACTIVADO");
            }
        }
        if (ACTDESACT.getSelectedItem().equals("DESACTIVADO")) 
        {
            obj1.DesactivarOscilar();
            if (obj1.DesactivarOscilar()==false) 
            {
                JOptionPane.showMessageDialog(null,"OSCILADOR DESACTIVADO");
            }
            
        }
        
    }//GEN-LAST:event_ACTDESACTActionPerformed

    private void ENCHUFARDESENCHUFARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENCHUFARDESENCHUFARActionPerformed
        // TODO add your handling code here:
        
        if (ENCHUFARDESENCHUFAR.getSelectedItem().equals("ENCHUFAR")) 
        {
            obj1.setEnchufado(true);
            jButtonAPAGAR.setEnabled(false);
            ACTDESACT.setEnabled(false);
            jButtonENCENDER.setEnabled(true);    
            
            JOptionPane.showMessageDialog(null, "Ventilador Enchufado");
        }
        
        if ((ENCHUFARDESENCHUFAR.getSelectedItem().equals("DESENCHUFAR"))&& (obj1.Enchufado==false)) 
        {
            JOptionPane.showMessageDialog(null, "No puede desenchufar el ventilador porque ya esta desenchufado" );
        }
        
        if ((ENCHUFARDESENCHUFAR.getSelectedItem().equals("DESENCHUFAR"))&& (obj1.Enchufado==true)) 
        {
            obj1.setEnchufado(false);
            jButtonSUBIR.setEnabled(false);
            jButtonBAJAR.setEnabled(false);
            jButtonAPAGAR.setEnabled(false);
            
        }
        
                
    }//GEN-LAST:event_ENCHUFARDESENCHUFARActionPerformed

       
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vista dialog = new vista(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ACTDESACT;
    private javax.swing.JComboBox<String> ENCHUFARDESENCHUFAR;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButtonAPAGAR;
    private javax.swing.JButton jButtonBAJAR;
    private javax.swing.JButton jButtonENCENDER;
    private javax.swing.JButton jButtonSUBIR;
    private javax.swing.JLabel jLabelOSCILADOR;
    private javax.swing.JLabel jLabelVELOCIDADACTUAL;
    private javax.swing.JLabel jLabelVELOCIDADACTUALNUM;
    private javax.swing.JLabel jLabelVELOCIDADMAXIMA;
    private javax.swing.JLabel jLabelVELOCIDADMAXIMANUM;
    private javax.swing.JPanel jPanelNUMVELMAX;
    private javax.swing.JPanel jPanelVELOCIDADACTUAL;
    // End of variables declaration//GEN-END:variables
}
